POST http://localhost:3000/subscribe HTTP/1.1
content-type: application/json

{
    "ping": "hello"
}

POST https://{zeit-deploy-url}/subscribe HTTP/1.1 
content-type: application/json

{
    "ping": "hello1"     
}

POST https://{zeit-deploy-url}/map HTTP/1.1
content-type: application/json

{
    "ping": "hello2"    
}
